
export interface Data {
  team_rank: number;
  team_name: string;
  winnerpoint: number;
  win: number;
  draw: number;
  lose: number;
  year: string;
  logo_url?: string;  // ロゴのURLを追加
  relegation_zone: boolean;
  acl_zone: boolean;
  play_off_zone: boolean;
}


export const rankData: Data[] = [{
  team_rank: 1,
  team_name: 'ヴィッセル神戸',
  winnerpoint: 71,
  win: 21,
  draw: 8,
  lose: 5,
  year: '2023',
  play_off_zone: false,
  acl_zone: true,
  relegation_zone: false,
  logo_url: 'kobe-logo.png',
}, {
  team_rank: 2,
  team_name: '横浜F・マリノス',
  winnerpoint: 64,
  win: 19,
  draw: 7,
  lose: 8,
  year: '2023',
  play_off_zone: false,
  acl_zone: true,
  relegation_zone: false,
  logo_url: 'marinos-logo.png'
}, {
  team_rank: 3,
  team_name: 'サンフレッチェ広島',
  winnerpoint: 58,
  win: 17,
  draw: 7,
  lose: 10,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'sanfrecce-logo.png'
}, {
  team_rank: 4,
  team_name: '浦和レッズ',
  winnerpoint: 57,
  win: 15,
  draw: 12,
  lose: 7,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'urawa-logo.png'
}, {
  team_rank: 5,
  team_name: '鹿島アントラーズ',
  winnerpoint: 52,
  win: 14,
  draw: 10,
  lose: 10,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kashima-logo.png'
}, {
  team_rank: 6,
  team_name: '名古屋グランパス',
  winnerpoint: 52,
  win: 14,
  draw: 10,
  lose: 10,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'nagoya-logo.png'
}, {
  team_rank: 7,
  team_name: 'アビスパ福岡',
  winnerpoint: 51,
  win: 15,
  draw: 6,
  lose: 13,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'fukuoka-logo.png'
},{
  team_rank: 8,
  team_name: '川崎フロンターレ',
  winnerpoint: 50,
  win: 14,
  draw: 8,
  lose: 12,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kawasaki-logo.png'
},{
  team_rank: 9,
  team_name: 'セレッソ大阪',
  winnerpoint: 49,
  win: 15,
  draw: 4,
  lose: 15,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'seresso-logo.png'
}, {
  team_rank: 10,
  team_name: 'アルビレックス新潟',
  winnerpoint: 45,
  win: 11,
  draw:12,
  lose: 11,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'niigata-logo.png'
},
{
  team_rank: 11,
  team_name: 'FC東京',
  winnerpoint: 43,
  win: 12,
  draw:7,
  lose: 15,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'fctokyo-logo.png'
},
{
  team_rank: 12,
  team_name: '北海道コンサドーレ札幌',
  winnerpoint: 40,
  win: 10,
  draw:10,
  lose: 14,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'sapporo-logo.png'
},
{
  team_rank: 13,
  team_name: '京都サンガF.C.',
  winnerpoint: 40,
  win: 12,
  draw:4,
  lose: 18,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kyoto-logo.png'
},
{
  team_rank: 14,
  team_name: 'サガン鳥栖',
  winnerpoint: 38,
  win: 9,
  draw:11,
  lose: 14,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'tosu-logo.png'
},
{
  team_rank: 15,
  team_name: '湘南ベルマーレ',
  winnerpoint: 34,
  win: 8,
  draw:10,
  lose: 16,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'shonan-logo.png'
},
{
  team_rank: 16,
  team_name: 'ガンバ大阪',
  winnerpoint: 34,
  win: 9,
  draw:7,
  lose: 18,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'gamba-logo.png'
},
{
  team_rank: 17,
  team_name: '柏レイソル',
  winnerpoint: 33,
  win: 6,
  draw:15,
  lose: 13,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kashiwa-logo.png'
},
{
  team_rank: 18,
  team_name: '横浜FC',
  winnerpoint: 29,
  win: 7,
  draw:8,
  lose: 19,
  year: '2023',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: true,
  logo_url: 'yokohamafc-logo.png'
},
//2022年の順位
{
  team_rank: 1,
  team_name: '横浜F・マリノス',
  winnerpoint: 68,
  win: 20,
  draw: 8,
  lose: 6,
  year: '2022',
  play_off_zone: false,
  acl_zone: true,
  relegation_zone: false,
  logo_url: 'marinos-logo.png'
},
{
  team_rank: 2,
  team_name: '川崎フロンターレ',
  winnerpoint: 66,
  win: 20,
  draw: 6,
  lose: 8,
  year: '2022',
  play_off_zone: false,
  acl_zone: true,
  relegation_zone: false,
  logo_url: 'kawasaki-logo.png'
},
{
  team_rank: 3,
  team_name: 'サンフレッチェ広島',
  winnerpoint: 68,
  win: 20,
  draw: 8,
  lose: 6,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'sanfrecce-logo.png'
},
{
  team_rank: 4,
  team_name: '鹿島アントラーズ',
  winnerpoint: 52,
  win: 13,
  draw: 13,
  lose: 8,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kashima-logo.png'
},
{
  team_rank: 5,
  team_name: 'セレッソ大阪',
  winnerpoint: 51,
  win: 13,
  draw: 12,
  lose: 9,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'seresso-logo.png'
},
{
  team_rank: 6,
  team_name: 'FC東京',
  winnerpoint: 49,
  win: 14,
  draw: 7,
  lose: 13,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'fctokyo-logo.png'
},
{
  team_rank: 7,
  team_name: '柏レイソル',
  winnerpoint: 47,
  win: 13,
  draw: 8,
  lose: 13,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kashiwa-logo.png'
},
{
  team_rank: 8,
  team_name: '名古屋グランパス',
  winnerpoint: 46,
  win: 11,
  draw: 13,
  lose: 10,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'nagoya-logo.png'
},
{
  team_rank: 9,
  team_name: '浦和レッズ',
  winnerpoint: 45,
  win: 10,
  draw: 15,
  lose: 9,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'urawa-logo.png'
},
{
  team_rank: 10,
  team_name: '北海道コンサドーレ札幌',
  winnerpoint: 45,
  win: 11,
  draw: 12,
  lose: 11,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'sapporo-logo.png'
},
{
  team_rank: 11,
  team_name: 'サガン鳥栖',
  winnerpoint: 42,
  win: 9,
  draw: 15,
  lose: 10,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'tosu-logo.png'
},
{
  team_rank: 12,
  team_name: '湘南ベルマーレ',
  winnerpoint: 41,
  win: 10,
  draw: 11,
  lose: 13,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'shonan-logo.png'
},
{
  team_rank: 13,
  team_name: 'ヴィッセル神戸',
  winnerpoint: 40,
  win: 11,
  draw: 7,
  lose: 16,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kobe-logo.png'
},
{
  team_rank: 14,
  team_name: 'アビスパ福岡',
  winnerpoint: 38,
  win: 9,
  draw: 11,
  lose: 14,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'fukuoka-logo.png'
},
{
  team_rank: 15,
  team_name: 'ガンバ大阪',
  winnerpoint: 37,
  win: 9,
  draw: 10,
  lose: 15,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'gamba-logo.png'
},
{
  team_rank: 16,
  team_name: '京都サンガF.C.',
  winnerpoint: 36,
  win: 8,
  draw: 12,
  lose: 14,
  year: '2022',
  play_off_zone: true,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kyoto-logo.png'
},
{
  team_rank: 17,
  team_name: '清水エスパルス',
  winnerpoint: 33,
  win: 7,
  draw: 12,
  lose: 15,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: true,
  logo_url: 'shimizu-logo.png'
},
{
  team_rank: 18,
  team_name: 'ジュビロ磐田',
  winnerpoint: 30,
  win: 6,
  draw: 12,
  lose: 16,
  year: '2022',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: true,
  logo_url: 'iwata-logo.png'
},
//2021順位表データ
{
  team_rank: 1,
  team_name: '川崎フロンターレ',
  winnerpoint: 92,
  win: 28,
  draw: 8,
  lose: 2,
  year: '2021',
  play_off_zone: false,
  acl_zone: true,
  relegation_zone: false,
  logo_url: 'kawasaki-logo.png'
},
{
  team_rank: 2,
  team_name: '横浜F・マリノス',
  winnerpoint: 73,
  win: 24,
  draw: 7,
  lose: 7,
  year: '2021',
  play_off_zone: false,
  acl_zone: true,
  relegation_zone: false,
  logo_url: 'marinos-logo.png'
},
{
  team_rank: 3,
  team_name: 'ヴィッセル神戸',
  winnerpoint: 73,
  win: 21,
  draw: 10,
  lose: 7,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kobe-logo.png'
},
{
  team_rank: 4,
  team_name: '鹿島アントラーズ',
  winnerpoint: 69,
  win: 21,
  draw: 6,
  lose: 11,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kashima-logo.png'
},
{
  team_rank: 5,
  team_name: '名古屋グランパス',
  winnerpoint: 66,
  win: 19,
  draw: 9,
  lose: 10,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'nagoya-logo.png'
},
{
  team_rank: 6,
  team_name: '浦和レッズ',
  winnerpoint: 63,
  win: 18,
  draw: 9,
  lose: 11,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'urawa-logo.png'
},
{
  team_rank: 7,
  team_name: 'サガン鳥栖',
  winnerpoint: 59,
  win: 16,
  draw: 11,
  lose: 11,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'tosu-logo.png'
},
{
  team_rank: 8,
  team_name: 'アビスパ福岡',
  winnerpoint:54,
  win: 14,
  draw: 12,
  lose: 12,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'fukuoka-logo.png'
}
,
{
  team_rank: 9,
  team_name: 'FC東京',
  winnerpoint: 53,
  win: 15,
  draw: 8,
  lose: 15,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'fctokyo-logo.png'
},
{
  team_rank: 10,
  team_name: '北海道コンサドーレ札幌',
  winnerpoint:51,
  win: 14,
  draw: 9,
  lose: 15,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'sapporo-logo.png'
}
,
{
  team_rank: 11,
  team_name: 'サンフレッチェ広島',
  winnerpoint: 49,
  win: 12,
  draw: 13,
  lose: 13,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'sanfrecce-logo.png'
},
{
  team_rank: 12,
  team_name: 'セレッソ大阪',
  winnerpoint:48,
  win: 13,
  draw: 9,
  lose: 16,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'seresso-logo.png'
}
,
{
  team_rank: 13,
  team_name: 'ガンバ大阪',
  winnerpoint:44,
  win: 12,
  draw: 8,
  lose: 18,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'gamba-logo.png'
}
,
{
  team_rank: 14,
  team_name: '清水エスパルス',
  winnerpoint:42,
  win: 10,
  draw: 12,
  lose: 16,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'shimizu-logo.png'
}
,
{
  team_rank: 15,
  team_name: '柏レイソル',
  winnerpoint:41,
  win: 12,
  draw: 5,
  lose: 21,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'kashiwa-logo.png'
}
,
{
  team_rank: 16,
  team_name: '湘南ベルマーレ',
  winnerpoint:37,
  win: 7,
  draw: 16,
  lose: 15,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: false,
  logo_url: 'shonan-logo.png'
}
,
{
  team_rank: 17,
  team_name: '徳島ヴォルティス',
  winnerpoint:36,
  win: 10,
  draw: 6,
  lose: 22,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: true,
  logo_url: 'tokushima-logo.png'
}
,
{
  team_rank: 18,
  team_name: '大分トリニータ',
  winnerpoint:35,
  win: 9,
  draw: 8,
  lose: 21,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: true,
  logo_url: 'oita-logo.png'
}
,
{
  team_rank: 19,
  team_name: 'ベガルタ仙台',
  winnerpoint:28,
  win: 5,
  draw: 13,
  lose: 20,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: true,
  logo_url: 'sendai-logo.png'
}
,
{
  team_rank: 20,
  team_name: '横浜FC',
  winnerpoint:27,
  win: 6,
  draw: 9,
  lose: 23,
  year: '2021',
  play_off_zone: false,
  acl_zone: false,
  relegation_zone: true,
  logo_url: 'yokohamafc-logo.png'
}
]
